"""add cart session pairing token

Revision ID: 2b87114328d5
Revises: 82d52c882a35
Create Date: 2026-01-30 14:39:02.455285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b87114328d5'
down_revision: Union[str, Sequence[str], None] = '82d52c882a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_session', sa.Column('pairing_token', sa.String(length=64), nullable=True))
    op.add_column('cart_session', sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'cart_session', ['pairing_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_session', type_='unique')
    op.drop_column('cart_session', 'paired_at')
    op.drop_column('cart_session', 'pairing_token')
    # ### end Alembic commands ###
