"""add camera_on to cart_session

Revision ID: 3fd7de1c788e
Revises: 4e8c53bbb5bf
Create Date: 2026-01-30 09:57:10.020006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd7de1c788e'
down_revision: Union[str, Sequence[str], None] = '4e8c53bbb5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_session', sa.Column('camera_on', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_session', 'camera_on')
    # ### end Alembic commands ###