"""remove cart session pairing fields

Revision ID: 4977b62bd2e4
Revises: 2b87114328d5
Create Date: 2026-01-30 14:50:33.934586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4977b62bd2e4'
down_revision: Union[str, Sequence[str], None] = '2b87114328d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_session_pairing_token_key'), 'cart_session', type_='unique')
    op.drop_column('cart_session', 'paired_at')
    op.drop_column('cart_session', 'pairing_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_session', sa.Column('pairing_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('cart_session', sa.Column('paired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('cart_session_pairing_token_key'), 'cart_session', ['pairing_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
