"""initial_migration

Revision ID: 4e8c53bbb5bf
Revises: 
Create Date: 2026-01-30 14:28:40.290367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '4e8c53bbb5bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', 'KAKAO', name='userprovider'), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_app_user_user_id'), 'app_user', ['user_id'], unique=False)
    op.create_table('cart_device',
    sa.Column('cart_device_id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('cart_device_id'),
    sa.UniqueConstraint('device_code')
    )
    op.create_index(op.f('ix_cart_device_cart_device_id'), 'cart_device', ['cart_device_id'], unique=False)
    op.create_table('product_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('zone_code', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_category_category_id'), 'product_category', ['category_id'], unique=False)
    op.create_table('recipe',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipe_recipe_id'), 'recipe', ['recipe_id'], unique=False)
    op.create_table('cart_session',
    sa.Column('cart_session_id', sa.Integer(), nullable=False),
    sa.Column('cart_device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CHECKOUT_REQUESTED', 'PAID', 'CANCELLED', name='cartsessionstatus'), nullable=False),
    sa.Column('budget_limit', sa.Integer(), nullable=True),
    sa.Column('expected_total_g', sa.Integer(), nullable=True),
    sa.Column('measured_total_g', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_device_id'], ['cart_device.cart_device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_session_id')
    )
    op.create_index(op.f('ix_cart_session_cart_session_id'), 'cart_session', ['cart_session_id'], unique=False)
    op.create_table('password_reset_token',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('payment_method',
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_type', sa.Enum('CARD', 'KAKAO_PAY', name='paymentmethodtype'), nullable=False),
    sa.Column('billing_key', sa.String(length=255), nullable=True),
    sa.Column('card_brand', sa.String(length=30), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('method_id')
    )
    op.create_index(op.f('ix_payment_method_method_id'), 'payment_method', ['method_id'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('unit_weight_g', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('product_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=False)
    op.create_table('saved_recipe',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('cart_detection_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('cart_session_id', sa.Integer(), nullable=False),
    sa.Column('cart_device_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('ADD', 'REMOVE', name='detectionactiontype'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detected_weight_g', sa.Integer(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_device_id'], ['cart_device.cart_device_id'], ),
    sa.ForeignKeyConstraint(['cart_session_id'], ['cart_session.cart_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_cart_detection_log_log_id'), 'cart_detection_log', ['log_id'], unique=False)
    op.create_table('cart_item',
    sa.Column('cart_item_id', sa.Integer(), nullable=False),
    sa.Column('cart_session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_session_id'], ['cart_session.cart_session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_index(op.f('ix_cart_item_cart_item_id'), 'cart_item', ['cart_item_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('cart_session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.Column('pg_provider', sa.Enum('KAKAO_PAY', 'CARD_PG', name='pgprovidertype'), nullable=False),
    sa.Column('pg_tid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cart_session_id'], ['cart_session.cart_session_id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['payment_method.method_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('cart_session_id')
    )
    op.create_index(op.f('ix_payment_payment_id'), 'payment', ['payment_id'], unique=False)
    op.create_table('recipe_ingredient',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_info', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'product_id')
    )
    op.create_table('ledger_entry',
    sa.Column('ledger_entry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('spend_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('GROCERY', 'MEAT', 'DAIRY', 'BEVERAGE', 'SNACK', 'HOUSEHOLD', 'ETC', name='ledgercategory'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_entry_id')
    )
    op.create_index(op.f('ix_ledger_entry_ledger_entry_id'), 'ledger_entry', ['ledger_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entry_ledger_entry_id'), table_name='ledger_entry')
    op.drop_table('ledger_entry')
    op.drop_table('recipe_ingredient')
    op.drop_index(op.f('ix_payment_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_cart_item_cart_item_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_cart_detection_log_log_id'), table_name='cart_detection_log')
    op.drop_table('cart_detection_log')
    op.drop_table('saved_recipe')
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_payment_method_method_id'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_cart_session_cart_session_id'), table_name='cart_session')
    op.drop_table('cart_session')
    op.drop_index(op.f('ix_recipe_recipe_id'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_product_category_category_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_cart_device_cart_device_id'), table_name='cart_device')
    op.drop_table('cart_device')
    op.drop_index(op.f('ix_app_user_user_id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
