"""make zone_code and category_id not null

Revision ID: 82d52c882a35
Revises: 5e709302d134
Create Date: 2026-01-30 14:09:57.462673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d52c882a35'
down_revision: Union[str, Sequence[str], None] = '5e709302d134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_session', 'camera_on')
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_category', 'zone_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_category', 'zone_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('cart_session', sa.Column('camera_on', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
